- hosts: all          #Especifico la validez del archivo (en este caso para todos los host)
  sudo: yes           #Se permite el uso de sudo
  remote_user: jmzero #Especifico el usuaro de la máquina

  tasks:
    #Se añade un repositorio con la version 3.6 de python, indicando donde encontrarlo.
  - name: Añadir repositorio de python 3.6
    become: true
    apt_repository: repo=ppa:deadsnakes/ppa state=present

    #Se actualiza el sistema por el comando update
  - name: Actualizar sistema
    become: true
    command: sudo apt-get update

    #Se instala python3.6 en caso de no estar instalado
  - name: Instalar Python 3.6
    become: true
    apt: pkg=python3.6 state=present

    #Se instala pip3
  - name: Instalacion de pip3
    become: true
    command: sudo apt-get -y install python3-pip

    #Se instala git para poder hacer uso del repositorio de GitHub en caso de no estar instalado
  - name: Instalar GitHub
    become: true
    command: sudo apt-get install -y git

    #Se clona el repositorio de GitHub
  - name: Clonar repositorio de GitHub
    git: repo=https://github.com/JmZero/Proyecto-IV.git dest=owstatistics/ force=yes

    #Se instalan las dependencias necesarias para el proyecto
  - name: Instalar Requerimientos
    command: pip3 install -r owstatistics/requirements.txt
