- hosts: all
  sudo: yes
  remote_user: jmzero

  tasks:
  - name: Añadir repositorio de python 3.6
    become: true
    apt_repository: repo=ppa:deadsnakes/ppa state=present

  - name: Actualizar sistema
    become: true
    command: sudo apt-get update

  - name: Instalar Python 3.6
    become: true
    apt: pkg=python3.6 state=present

  - name: Instalacion de pip3
    become: true
    command: sudo apt-get -y install python3-pip

  - name: Instalar GitHub
    become: true
    command: sudo apt-get install -y git

  - name: Clonar repositorio de GitHub
    git: repo=https://github.com/JmZero/Proyecto-IV.git dest=owstatistics/ force=yes

  - name: Instalar Requerimientos
    command: pip3 install -r owstatistics/requirements.txt
